### ISSUE TITLE
Not respecting my .csscomb.json config

### ISSUE THREAD

**Issue by ThinkGraphical** [1000ch/atom-csscomb#15]
Having an issue with atom-csscomb not respecting my config defined in .csscomb.json.

I'm trying to sort includes, variables,... on top like so:

```
...
"sort-order": [
        [
            "$variable",
            "$import",
            "$extend",
            "$include"
        ],
        [
            "font",
            "font-family",
            "font-size",
            "font-weight",
            "font-style",
            "font-variant",
            "font-size-adjust",
            "font-stretch",
            "font-effect",
            "font-emphasize",
            "font-emphasize-position",
            "font-emphasize-style",
            "font-smooth",
            "line-height"
        ],
...
```

But the output still seems to be the default preset:

```
.tiles-listing {
    font-size: 0;
    margin: 0 $padding-large-horizontal*0.8;
    margin-bottom: $padding-large-vertical;
    @include clearfix();

    .tile-item {
        position: relative;
        float: left;
        width: 50%;
        padding-bottom: 50%;
        margin: 0;
        color: #fff;
        border-radius: 0 !important;
        @extend .card;
        border: $padding-large-horizontal*0.2 solid $base-background-color;
        font-size: $font-size-base;
    }
}
```

How can I debug this properly?

**Comment by 1000ch** [comment]
Fixed in `v1.9.3`.

**Comment by ryanaltvater** [comment]
I'm still having this issue...

```
        [
            "$import"
        ],
        [
            "$variable"
        ],
        [
            "$extend"
        ],
        [
            "$include"
        ],
        [
            "$include media small",
            "$include media medium",
            "$include media large",
            "$include media x-large",
            "$media"
        ],
```

Output...

```
    @import "";

    $test: #000;

    @include media($large) {}
    @include media($small) {}
    @include font-size(14px);
    @include media($x-large) {}
    @include media($medium) {}
    @extend .test;

    position: absolute;
    top: 50%;
    left: 50%;
    width: 100%;
    font-weight: bold;
    color: red;
    -webkit-transform: translate(-50%, -50%);
       -moz-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
         -o-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);

    @media (min-width: 768px) and (max-width: 1023px) {}
```

Desired output...

```
    @import "";

    $test: #000;

    @extend .test;

    @include font-size(14px);

    @include media($small) {}
    @include media($medium) {}
    @include media($large) {}
    @include media($x-large) {}
    @media (min-width: 768px) and (max-width: 1023px) {}

    position: absolute;
    top: 50%;
    left: 50%;
    width: 100%;
    font-weight: bold;
    color: red;
    -webkit-transform: translate(-50%, -50%);
       -moz-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
         -o-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
```

Can you help shed some light on what I might be doing wrong? Thanks in advance. I've been searching and trying to debug this for a couple hours now.

**Comment by ghost** [comment]
I am having this issue as well.

I have a csscomb.json in my root directory that specifies these styles:

```
    [
            "$include",
            "display",
            "position",
            "z-index",
            "top",
            "right",
            "bottom",
            "left",
            "width",
            "height",
            "margin",
            "color",  ...
```

I'm running CSS Comb in Atom and getting this incorrect output:

```
  .header {
    height: 264px;
    color: $color-n10;
    background-color: $color-n2;
    @include block_rel;
    @include proxima_nova;

    .timeline_region {
      z-index: 0;
      top: 0;
      width: 100%;
      @include block_abs;
    }

    .header_content {
      z-index: 1;
      padding: 28px;
      text-align: center;
      background-color: $color-n2;
      @include block_rel;
    }

    .header_content .title {
      font-size: 24px;
    }

    .header_content .sub_title {
      font-size: 14px;
      margin-top: 10px;
      color: $color-n4;
    }
  }
```
